before_script:
  - gem update --system
  - gem install bundler -v '~>1.13'
  - bundler --version
  - ./bin/install.sh

stages:
  - test
  - release

test_23:
  image: ruby:2.3
  stage: test
  environment: test
  only:
    - tags
  script:
    - ./bin/test.sh

test_24:
  image: ruby:2.4.0
  stage: test
  environment: test
  only:
    - tags
  script:
    - ./bin/test.sh

test_25:
  image: ruby:2.5.0
  stage: test
  environment: test
  only:
    - tags
  script:
    - ./bin/test.sh

release:
  image: ruby:2.5.0
  stage: release
  environment: gem
  only:
    - tags
  script:
    -
    - ''
    - ./bin/release.sh
