
name: CI

env:
  LANG: C.UTF-8
  GEM_NAME: thefox-ext
  GEMSPEC_FILE: thefox-ext.gemspec

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - '2.3'
          # - '2.4'
          # - '2.5'
          # - '2.6'
          # - '2.7'
          # - '3.0'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        #uses: ruby/setup-ruby@473e4d8fe5dd94ee328fdfca9f8c9c7afc9dae5e
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Setup Rubygems
        run: |
          mkdir -p ~/.gem
          printf "%s\n:rubygems_api_key: %s" "---" "${RUBYGEMSORG_API_KEY}" > ~/.gem/credentials; chmod 0600 ~/.gem/credentials
      - name: Install
        run: ./bin/install.sh
      - name: Run tests
        run: ./bin/test.sh
